; PlatformIO Project Configuration File
;
; FU Winch v2 - RP2040 Eval
; Board: Waveshare RP2040-Zero
; Framework: Arduino
;
; Based on v1 FU_WINCH_RP2040_U2
; For 3-unit motion test with v2 evaluation board

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino

; Serial Monitor
monitor_speed = 115200

; Upload settings
upload_speed = 921600

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=0

; Library dependencies
lib_deps =
    adafruit/Adafruit NeoPixel@^1.12.0
    waspinator/AccelStepper@^1.64
    teemuatlut/TMCStepper@^0.7.3
    wire
