[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit NeoPixel@^1.12.0
    teemuatlut/TMCStepper@^0.7.3
    waspinator/AccelStepper@^1.64
    bblanchon/ArduinoJson@^7.2.3
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DENABLE_DEBUG_SERIAL

; AWS S3 Upload Settings
custom_s3_bucket = comone-fragmented-unity-fw
custom_s3_prefix = winch_v2/
custom_aws_region = ap-northeast-1
custom_firmware_name = winch

extra_scripts =
    post:scripts/upload_to_s3.py
