[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel
    adafruit/Adafruit AMG88xx Library
    adafruit/Adafruit BNO055
    adafruit/Adafruit Unified Sensor
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DNODE_UNIT_1
    -DNODE_UNIT_1

board_build.partitions = default_8MB.csv
board_upload.flash_size = 8MB

; Custom S3 Upload Settings
custom_s3_bucket = comone-fragmented-unity-fw
custom_s3_prefix = tube_v2_unit1/
custom_aws_region = ap-northeast-1
custom_firmware_name = tube_unit1

; Run S3 upload script after build
extra_scripts = post:scripts/upload_to_s3.py
