[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
lib_deps =
    https://github.com/simplefoc/Arduino-FOC.git#dev
    Wire
monitor_speed = 115200
build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DSIMPLEFOC_ESP32_USE_LEDC
    -DNODE_UNIT_2
    -DFIRMWARE_VERSION="2.0.0"

; Custom S3 Upload Settings
custom_s3_bucket = comone-fragmented-unity-fw
custom_s3_prefix =
custom_aws_region = ap-northeast-1
custom_firmware_name = tube_v2_unit2

; Run S3 upload script after build
extra_scripts = post:scripts/upload_to_s3.py
